// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.1
// source: proto/redirect.proto

package redirectpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RedirectShortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortLink     string                 `protobuf:"bytes,1,opt,name=short_link,json=shortLink,proto3" json:"short_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedirectShortRequest) Reset() {
	*x = RedirectShortRequest{}
	mi := &file_proto_redirect_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedirectShortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedirectShortRequest) ProtoMessage() {}

func (x *RedirectShortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redirect_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedirectShortRequest.ProtoReflect.Descriptor instead.
func (*RedirectShortRequest) Descriptor() ([]byte, []int) {
	return file_proto_redirect_proto_rawDescGZIP(), []int{0}
}

func (x *RedirectShortRequest) GetShortLink() string {
	if x != nil {
		return x.ShortLink
	}
	return ""
}

type RedirectShortResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrigLink      string                 `protobuf:"bytes,1,opt,name=orig_link,json=origLink,proto3" json:"orig_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedirectShortResponse) Reset() {
	*x = RedirectShortResponse{}
	mi := &file_proto_redirect_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedirectShortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedirectShortResponse) ProtoMessage() {}

func (x *RedirectShortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redirect_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedirectShortResponse.ProtoReflect.Descriptor instead.
func (*RedirectShortResponse) Descriptor() ([]byte, []int) {
	return file_proto_redirect_proto_rawDescGZIP(), []int{1}
}

func (x *RedirectShortResponse) GetOrigLink() string {
	if x != nil {
		return x.OrigLink
	}
	return ""
}

var File_proto_redirect_proto protoreflect.FileDescriptor

const file_proto_redirect_proto_rawDesc = "" +
	"\n" +
	"\x14proto/redirect.proto\x12\bredirect\"5\n" +
	"\x14RedirectShortRequest\x12\x1d\n" +
	"\n" +
	"short_link\x18\x01 \x01(\tR\tshortLink\"4\n" +
	"\x15RedirectShortResponse\x12\x1b\n" +
	"\torig_link\x18\x01 \x01(\tR\borigLink2`\n" +
	"\x0fRedirectService\x12M\n" +
	"\n" +
	"ToRedirect\x12\x1e.redirect.RedirectShortRequest\x1a\x1f.redirect.RedirectShortResponseB\x13Z\x11/proto/redirectpbb\x06proto3"

var (
	file_proto_redirect_proto_rawDescOnce sync.Once
	file_proto_redirect_proto_rawDescData []byte
)

func file_proto_redirect_proto_rawDescGZIP() []byte {
	file_proto_redirect_proto_rawDescOnce.Do(func() {
		file_proto_redirect_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_redirect_proto_rawDesc), len(file_proto_redirect_proto_rawDesc)))
	})
	return file_proto_redirect_proto_rawDescData
}

var file_proto_redirect_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_redirect_proto_goTypes = []any{
	(*RedirectShortRequest)(nil),  // 0: redirect.RedirectShortRequest
	(*RedirectShortResponse)(nil), // 1: redirect.RedirectShortResponse
}
var file_proto_redirect_proto_depIdxs = []int32{
	0, // 0: redirect.RedirectService.ToRedirect:input_type -> redirect.RedirectShortRequest
	1, // 1: redirect.RedirectService.ToRedirect:output_type -> redirect.RedirectShortResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_redirect_proto_init() }
func file_proto_redirect_proto_init() {
	if File_proto_redirect_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_redirect_proto_rawDesc), len(file_proto_redirect_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_redirect_proto_goTypes,
		DependencyIndexes: file_proto_redirect_proto_depIdxs,
		MessageInfos:      file_proto_redirect_proto_msgTypes,
	}.Build()
	File_proto_redirect_proto = out.File
	file_proto_redirect_proto_goTypes = nil
	file_proto_redirect_proto_depIdxs = nil
}
