// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.1
// source: proto/shortener.proto

package shortenerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrigLink      string                 `protobuf:"bytes,1,opt,name=orig_link,json=origLink,proto3" json:"orig_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortRequest) Reset() {
	*x = ShortRequest{}
	mi := &file_proto_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortRequest) ProtoMessage() {}

func (x *ShortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortRequest.ProtoReflect.Descriptor instead.
func (*ShortRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *ShortRequest) GetOrigLink() string {
	if x != nil {
		return x.OrigLink
	}
	return ""
}

type ShortResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortLink     string                 `protobuf:"bytes,1,opt,name=short_link,json=shortLink,proto3" json:"short_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortResponse) Reset() {
	*x = ShortResponse{}
	mi := &file_proto_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortResponse) ProtoMessage() {}

func (x *ShortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortResponse.ProtoReflect.Descriptor instead.
func (*ShortResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *ShortResponse) GetShortLink() string {
	if x != nil {
		return x.ShortLink
	}
	return ""
}

var File_proto_shortener_proto protoreflect.FileDescriptor

const file_proto_shortener_proto_rawDesc = "" +
	"\n" +
	"\x15proto/shortener.proto\x12\bredirect\"+\n" +
	"\fShortRequest\x12\x1b\n" +
	"\torig_link\x18\x01 \x01(\tR\borigLink\".\n" +
	"\rShortResponse\x12\x1d\n" +
	"\n" +
	"short_link\x18\x01 \x01(\tR\tshortLink2N\n" +
	"\x10ShortenerService\x12:\n" +
	"\aToShort\x12\x16.redirect.ShortRequest\x1a\x17.redirect.ShortResponseB\x14Z\x12/proto/shortenerpbb\x06proto3"

var (
	file_proto_shortener_proto_rawDescOnce sync.Once
	file_proto_shortener_proto_rawDescData []byte
)

func file_proto_shortener_proto_rawDescGZIP() []byte {
	file_proto_shortener_proto_rawDescOnce.Do(func() {
		file_proto_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_shortener_proto_rawDesc), len(file_proto_shortener_proto_rawDesc)))
	})
	return file_proto_shortener_proto_rawDescData
}

var file_proto_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_shortener_proto_goTypes = []any{
	(*ShortRequest)(nil),  // 0: redirect.ShortRequest
	(*ShortResponse)(nil), // 1: redirect.ShortResponse
}
var file_proto_shortener_proto_depIdxs = []int32{
	0, // 0: redirect.ShortenerService.ToShort:input_type -> redirect.ShortRequest
	1, // 1: redirect.ShortenerService.ToShort:output_type -> redirect.ShortResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_shortener_proto_init() }
func file_proto_shortener_proto_init() {
	if File_proto_shortener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_shortener_proto_rawDesc), len(file_proto_shortener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_shortener_proto_goTypes,
		DependencyIndexes: file_proto_shortener_proto_depIdxs,
		MessageInfos:      file_proto_shortener_proto_msgTypes,
	}.Build()
	File_proto_shortener_proto = out.File
	file_proto_shortener_proto_goTypes = nil
	file_proto_shortener_proto_depIdxs = nil
}
